import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
export const metadata: Metadata = { title: "TRS — Electrical Device Assembly Technician", description: "Martin Li’s paid, part-time electrical assembly role at TRS: cable and wire-harness assembly, electrical testing, quality checks, and troubleshooting." };
const photos = [
 {file:"32394.jpg",label:"CABLE ASSEMBLIES",caption:"A batch on the bench—lots of small connections and labels to keep track of.",alt:"A tray of labeled cable assemblies with metal connectors and white multi-wire plugs"},
 {file:"32393.jpg",label:"THE TEST BENCH",caption:"This is the CableEye setup I use to check the wiring.",alt:"CableEye electrical cable tester with connector adapter boards and expansion test banks"},
 {file:"32392.jpg",label:"A CLOSER LOOK",caption:"Different connectors, same goal: making sure the connections are right.",alt:"Close view of CableEye connector boards with a cable attached and a green pass indicator"},
 {file:"32395.jpg",label:"CONNECTOR DETAILS",caption:"Some of the larger cable connectors, with their clamps and labels up close.",alt:"Several black cables with metal circular connectors, cable clamps, and blue identification labels"}
];
export default function TrsExperience(){return <main id="main">
 <section className="project-heading shell"><Link href="/#experience" className="back-link"><ArrowLeft size={15}/>BACK TO OVERVIEW</Link><div className="project-title-row"><div><p className="eyebrow">WORK EXPERIENCE / TRS</p><h1>Electrical Device<br/>Assembly Technician</h1></div><div className="project-title-detail"><p>TRS International Manufacturing, Inc.</p><span>PAID POSITION · PART-TIME</span><p className="trs-role-date">August 2026 — Present<br/>Foothill Ranch, California · On-site</p></div></div></section>
 <section className="project-detail-body shell"><p className="detail-lead">I build and test cable assemblies and wire harnesses at TRS. My work combines hands-on assembly with electrical checks: following the drawing, making the connections, and working through issues when the test results don’t match what’s expected.</p><div className="detail-columns"><div><h2>What I do</h2><ul className="experience-points"><li><strong>Assemble to instructions.</strong> Follow customer drawings and work instructions to put together cable assemblies and wire harnesses.</li><li><strong>Prepare and connect wiring.</strong> Use hand tools for wire preparation and terminal work, then route wires and check connector and cable labels.</li><li><strong>Test the assembly.</strong> Operate electrical test equipment, including the CableEye setup shown below, and interpret the results.</li><li><strong>Check and troubleshoot.</strong> Inspect the assembly for quality, investigate wiring or connection issues, and work with the production team to resolve problems.</li></ul><a href="https://www.ziprecruiter.com/c/trs-international-mfg/Job/Assembler-Production-Line-Worker/-in-Lake-Forest,CA?jid=4da0798b632beed7" className="source-link" target="_blank" rel="noopener noreferrer">TRS role description<ArrowUpRight size={13}/></a></div><div><h2>From assembly to a checked connection.</h2><p>Small details matter here: matching a wire to the right connection, keeping the routing organized, and making labels easy to follow.</p><p>Testing gives me a way to check the physical work. I read the results and use them to guide troubleshooting, rather than relying on appearance alone.</p><div className="role-skills"><span>Wire-harness assembly</span><span>Drawings & work instructions</span><span>Electrical testing</span><span>Quality checks</span><span>Troubleshooting</span></div></div></div></section>
 <section className="trs-company shell" aria-labelledby="trs-company-title"><div><p className="eyebrow">ABOUT THE COMPANY</p><h2 id="trs-company-title">TRS International Manufacturing</h2><p>TRS manufactures custom cable assemblies and wire harnesses for aerospace, defense, medical devices, and other demanding applications. Its work spans prototype builds through production, with an emphasis on consistent assembly processes and traceability.</p><a href="https://www.trsintl.com/" target="_blank" rel="noopener noreferrer" className="text-link">Visit TRS’s official website<ArrowUpRight size={16}/></a></div><figure><img src="/gallery/trs/company-harness.jpg" alt="Aerospace and defense cable harness product example from TRS’s official website" loading="lazy"/><figcaption>Company product example · <a href="https://www.trsintl.com/" target="_blank" rel="noopener noreferrer">Image: TRS International Manufacturing</a></figcaption></figure></section>
 <section className="flight-journal shell" aria-labelledby="trs-journal-title"><div className="journal-heading"><p className="eyebrow">FROM MY WORKBENCH</p><h2 id="trs-journal-title">A few details from my day.</h2><p>The assemblies I work with and the equipment behind the checks.</p></div><div className="journal-grid">{photos.map((photo,i)=><figure className="journal-entry" key={photo.file}><a href={`/gallery/trs/${photo.file}`} target="_blank" rel="noopener noreferrer" aria-label={`Open full photo: ${photo.alt}`}><img src={`/gallery/trs/${photo.file}`} alt={photo.alt} loading="lazy"/></a><figcaption><span>{String(i+1).padStart(2,'0')} / {photo.label}</span>{photo.caption}</figcaption></figure>)}</div></section>
 <section className="project-end shell"><Link href="/#projects" className="text-link"><ArrowLeft size={16}/>Engineering projects</Link><Link href="/#contact" className="text-link">Contact me<ArrowUpRight size={17}/></Link></section>
 </main>}
