"use client";
import {useEffect,useRef,useState} from "react";
import {ZoomIn,ZoomOut,RotateCcw,Maximize,Minimize,Box,ArrowUpRight} from "lucide-react";
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from "@/components/ui/select";
import {Switch} from "@/components/ui/switch";
import {Slider} from "@/components/ui/slider";
import {Dialog,DialogContent,DialogTitle,DialogDescription} from "@/components/ui/dialog";
import {modelInfo,type ModelPart} from "@/lib/rocket-model";
import type {PerspectiveCamera,Group,WebGLRenderer} from "three";
import type {OrbitControls} from "three/addons/controls/OrbitControls.js";
type Engine={camera:PerspectiveCamera;controls:OrbitControls;renderer:WebGLRenderer;model:Group;reset:()=>void};
export function RocketViewer({hero=false}:{hero?:boolean}){
 const canvasHost=useRef<HTMLDivElement>(null),labelHost=useRef<SVGSVGElement>(null),engine=useRef<Engine|null>(null);
 const [part,setPart]=useState<ModelPart>('assembly'),[wireframe,setWireframe]=useState(false),[internals,setInternals]=useState(false),[spin,setSpin]=useState(false),[labels,setLabels]=useState(true),[separation,setSeparation]=useState(0),[expanded,setExpanded]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 const live=useRef({spin,labels,separation});live.current={spin,labels,separation};
 useEffect(()=>{setSpin(hero&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches);},[hero]);
 useEffect(()=>{
  let disposed=false,cleanup=()=>{};setReady(false);setError(false);
  Promise.all([import('three'),import('three/addons/controls/OrbitControls.js'),import('three/addons/environments/RoomEnvironment.js'),import('@/lib/rocket-model')]).then(([T,{OrbitControls},{RoomEnvironment},{buildRocket,getRocketRecords,updateRocketSeparation,disposeModel}])=>{
   if(disposed||!canvasHost.current)return;const host=canvasHost.current;let renderer:WebGLRenderer;
   try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setError(true);return;}
   renderer.setPixelRatio(Math.min(window.devicePixelRatio,2));renderer.setClearColor(0,0);renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;
   const canvas=renderer.domElement;canvas.tabIndex=0;canvas.setAttribute('aria-label',`Interactive ${modelInfo[part].name}. Drag to rotate, scroll or pinch to zoom. Arrow keys rotate, plus and minus zoom, R resets.`);host.appendChild(canvas);
   const scene=new T.Scene(),camera=new T.PerspectiveCamera(32,1,.001,100),model=buildRocket(part,wireframe,internals);scene.add(model);if(hero)model.rotation.z=-.25;
   const pmrem=new T.PMREMGenerator(renderer),room=new RoomEnvironment(),environment=pmrem.fromScene(room,.04);scene.environment=environment.texture;room.dispose();pmrem.dispose();
   scene.add(new T.HemisphereLight(0xffffff,0x393939,1.6));const key=new T.DirectionalLight(0xffffff,3);key.position.set(-3,4,5);scene.add(key);const rim=new T.DirectionalLight(0xffffff,2.4);rim.position.set(3,1,-4);scene.add(rim);
   const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.dampingFactor=.09;controls.enablePan=!hero;controls.rotateSpeed=.65;controls.zoomSpeed=.7;controls.autoRotateSpeed=hero?.28:.7;controls.enableZoom=!hero;
   const records=getRocketRecords(model);let shownSeparation=hero?0:live.current.separation/100;updateRocketSeparation(model,shownSeparation);
   const bounds=()=>{model.updateMatrixWorld(true);const box=new T.Box3();for(const record of records)if(record.group.visible)box.expandByObject(record.group);if(part==='recovery'){box.expandByObject(model.userData.shrouds);box.expandByObject(model.userData.cordGroup);}return box;};
   const fitDistance=(box:InstanceType<typeof T.Box3>)=>{const s=box.getSize(new T.Vector3()),v=T.MathUtils.degToRad(camera.fov),h=2*Math.atan(Math.tan(v/2)*camera.aspect);return Math.max(s.y/(2*Math.tan(v/2)),s.x/(2*Math.tan(h/2)),s.z/(2*Math.tan(h/2)))*(hero?1.22:1.48);};
   let previousFit=1;
   const reset=()=>{const b=bounds(),c=b.getCenter(new T.Vector3());previousFit=fitDistance(b);controls.target.copy(c);const direction=part==='ring'?new T.Vector3(.25,.55,1):new T.Vector3(.23,.08,1);camera.position.copy(c).add(direction.normalize().multiplyScalar(previousFit));controls.minDistance=.1;controls.maxDistance=12;controls.update();};
   let firstResize=true;
   const resize=()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();if(firstResize){reset();firstResize=false;}if(labelHost.current)labelHost.current.setAttribute('viewBox',`0 0 ${w} ${h}`);};resize();const observer=new ResizeObserver(resize);observer.observe(host);
   const svg=labelHost.current,ns='http://www.w3.org/2000/svg';
   const annotationItems=!hero&&svg?records.filter(r=>r.group.visible).map(record=>{const g=document.createElementNS(ns,'g'),path=document.createElementNS(ns,'path'),dot=document.createElementNS(ns,'circle'),text=document.createElementNS(ns,'text');path.setAttribute('fill','none');path.setAttribute('stroke','#737373');path.setAttribute('stroke-width','.65');dot.setAttribute('r','2');dot.setAttribute('fill','#aaa');text.textContent=record.label;text.setAttribute('fill','#c1c1c1');g.append(path,dot,text);svg.appendChild(g);return{record,g,path,dot,text,px:0,py:0,ly:0};}):[];
   const annotate=()=>{
    if(!svg)return;svg.style.opacity=live.current.labels?'1':'0';if(!live.current.labels)return;
    const w=host.clientWidth,h=host.clientHeight;const sides=[annotationItems.filter(i=>i.record.side<0),annotationItems.filter(i=>i.record.side>0)];
    for(const item of annotationItems){const point=item.record.group.localToWorld(item.record.anchor.clone()).project(camera);item.px=(point.x+1)*w/2;item.py=(1-point.y)*h/2;item.ly=item.py;item.g.style.display=point.z>1||point.z<-1?'none':'';}
    for(const [side,items]of sides.entries()){
     items.sort((a,b)=>a.py-b.py);const gap=w<500?20:23,min=70,max=h-112;let previous=min-gap;
     for(const item of items){item.ly=Math.max(previous+gap,Math.min(max,item.ly));previous=item.ly;}
     const overflow=items.length?Math.max(0,items[items.length-1].ly-max):0;for(const item of items)item.ly-=overflow;
     for(const item of items){const left=side===0,tx=left?18:w-18,end=left?(w<500?108:130):w-(w<500?108:130);item.path.setAttribute('d',`M ${item.px.toFixed(1)} ${item.py.toFixed(1)} L ${end} ${item.ly.toFixed(1)} L ${left?tx:tx} ${item.ly.toFixed(1)}`);item.dot.setAttribute('cx',String(item.px));item.dot.setAttribute('cy',String(item.py));item.text.setAttribute('x',String(tx));item.text.setAttribute('y',String(item.ly-6));item.text.setAttribute('text-anchor',left?'start':'end');}
    }
   };
   let visible=true;const visibility=new IntersectionObserver(([e])=>{visible=e.isIntersecting});visibility.observe(host);let frame=0,last=performance.now();
   const draw=(now:number)=>{frame=requestAnimationFrame(draw);if(!visible||document.hidden)return;const delta=Math.min((now-last)/1000,.05);last=now;const target=hero?0:live.current.separation/100;
    if(Math.abs(target-shownSeparation)>.0004){shownSeparation=window.matchMedia('(prefers-reduced-motion: reduce)').matches?target:T.MathUtils.lerp(shownSeparation,target,.18);if(Math.abs(target-shownSeparation)<.0004)shownSeparation=target;updateRocketSeparation(model,shownSeparation);const b=bounds(),nextFit=fitDistance(b),center=b.getCenter(new T.Vector3()),offset=camera.position.clone().sub(controls.target);offset.multiplyScalar(nextFit/previousFit);controls.target.copy(center);camera.position.copy(center).add(offset);previousFit=nextFit;}
    controls.autoRotate=live.current.spin;controls.update(delta);model.updateMatrixWorld(true);renderer.render(scene,camera);annotate();};frame=requestAnimationFrame(draw);
   const zoom=(factor:number)=>{const v=camera.position.clone().sub(controls.target);v.setLength(Math.max(controls.minDistance,Math.min(controls.maxDistance,v.length()*factor)));camera.position.copy(controls.target).add(v);controls.update();};
   const keydown=(e:KeyboardEvent)=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','+','=','-','r','R'].includes(e.key))return;e.preventDefault();if(e.key==='+'||e.key==='=')zoom(.82);else if(e.key==='-')zoom(1.22);else if(e.key.toLowerCase()==='r')reset();else{const s=new T.Spherical().setFromVector3(camera.position.clone().sub(controls.target));if(e.key==='ArrowLeft')s.theta-=.12;if(e.key==='ArrowRight')s.theta+=.12;if(e.key==='ArrowUp')s.phi-=.12;if(e.key==='ArrowDown')s.phi+=.12;s.makeSafe();camera.position.copy(controls.target).add(new T.Vector3().setFromSpherical(s));controls.update();}};
   const lost=(e:Event)=>{e.preventDefault();setError(true);setReady(false);};canvas.addEventListener('keydown',keydown);canvas.addEventListener('webglcontextlost',lost);const manual=()=>{if(hero)setSpin(false)};controls.addEventListener('start',manual);
   engine.current={camera,controls,renderer,model,reset};setReady(true);
   cleanup=()=>{cancelAnimationFrame(frame);observer.disconnect();visibility.disconnect();canvas.removeEventListener('keydown',keydown);canvas.removeEventListener('webglcontextlost',lost);controls.dispose();disposeModel(model);environment.dispose();renderer.dispose();canvas.remove();annotationItems.forEach(i=>i.g.remove());engine.current=null;};
  }).catch(()=>{if(!disposed)setError(true)});
  return()=>{disposed=true;cleanup();};
 },[hero,part,wireframe,internals,expanded,retry]);
 const zoom=(factor:number)=>{const e=engine.current;if(!e)return;const v=e.camera.position.clone().sub(e.controls.target);v.setLength(Math.max(e.controls.minDistance,Math.min(e.controls.maxDistance,v.length()*factor)));e.camera.position.copy(e.controls.target).add(v);e.controls.update();};
 const stage=<div className="model-stage"><div className="model-canvas" ref={canvasHost}/>{!hero&&<svg className="annotation-overlay" ref={labelHost} aria-hidden="true"/>}{!ready&&!error&&<div className="model-loading" role="status"><Box size={21}/><span>Loading flight hardware</span></div>}{error&&<div className="model-fallback"><img src="/models/rocket-profile.svg" alt="Dimensioned rocket profile"/><p>3D viewing is unavailable in this browser.</p>{!hero&&<><button className="text-link" onClick={()=>setRetry(n=>n+1)}>Retry viewer</button><a href="/files/rocket-2.ork" download className="text-link">Download design<ArrowUpRight size={14}/></a></>}</div>}{!hero&&<><div className="stage-caption eyebrow"><span>FLIGHT HARDWARE / {part==='assembly'?'FULL ASSEMBLY':part.toUpperCase()}</span><span>{separation===0?'ASSEMBLED':`${separation}% SEPARATED`}</span></div><div className="stage-bottom"><span>DRAG TO ROTATE · SCROLL TO ZOOM</span><div className="viewer-buttons"><button onClick={()=>zoom(.8)} disabled={!ready} title="Zoom in" aria-label="Zoom in"><ZoomIn size={18}/></button><button onClick={()=>zoom(1.25)} disabled={!ready} title="Zoom out" aria-label="Zoom out"><ZoomOut size={18}/></button><button onClick={()=>engine.current?.reset()} disabled={!ready} title="Reset view" aria-label="Reset view"><RotateCcw size={17}/></button><button onClick={()=>setExpanded(!expanded)} title={expanded?'Exit expanded view':'Expand viewer'} aria-label={expanded?'Exit expanded view':'Expand viewer'} aria-pressed={expanded}>{expanded?<Minimize size={17}/>:<Maximize size={17}/>}</button></div></div></>}</div>;
 if(hero)return <div className="hero-viewer">{stage}<button className="hero-pause" onClick={()=>setSpin(!spin)} aria-pressed={spin}>{spin?'PAUSE ROTATION':'ROTATE MODEL'}</button></div>;
 const info=modelInfo[part];const explorer=<div className={`rocket-explorer ${expanded?'is-expanded':''}`}>
 {stage}<aside className="model-inspector"><p className="eyebrow">Hardware explorer</p><label className="inspector-label" htmlFor="component-select">Select assembly</label><Select value={part} onValueChange={v=>{setPart(v as ModelPart);setSeparation(0)}}><SelectTrigger id="component-select" className="w-full h-11 rounded-none border-zinc-700"><SelectValue/></SelectTrigger><SelectContent position="popper" className="rounded-none z-[100]">{Object.entries(modelInfo).map(([key,value])=><SelectItem key={key} value={key} className="py-3">{value.name}</SelectItem>)}</SelectContent></Select><div className="explosion-control"><div><label htmlFor="separation">Part separation</label><output>{separation}%</output></div><Slider id="separation" thumbLabel="Part separation" thumbValueText={`${separation} percent separated`} value={[separation]} min={0} max={100} step={1} onValueChange={v=>setSeparation(v[0])} disabled={!ready}/><div className="slider-endpoints"><button onClick={()=>setSeparation(0)} disabled={!ready}>Assembled</button><button onClick={()=>setSeparation(100)} disabled={!ready}>Exploded</button></div></div><p className="component-subtitle">{info.subtitle}</p><dl className="component-dimensions">{info.dimensions.map(([name,value])=><div key={name}><dt>{name}</dt><dd>{value}</dd></div>)}</dl><div className="viewer-switches"><label htmlFor="part-labels">Part labels<Switch id="part-labels" checked={labels} onCheckedChange={setLabels}/></label><label htmlFor="wireframe">Wireframe<Switch id="wireframe" checked={wireframe} onCheckedChange={setWireframe}/></label><label htmlFor="internals">Reveal internals<Switch id="internals" checked={internals} onCheckedChange={setInternals}/></label><label htmlFor="auto-rotate">Auto-rotate<Switch id="auto-rotate" checked={spin} onCheckedChange={setSpin}/></label></div><p className="viewer-source">Reconstructed from the rocket design and reference photos. Recovery shapes and motor exterior are illustrative.</p></aside></div>;
 return expanded?<Dialog open onOpenChange={setExpanded}><DialogContent className="expanded-model-dialog" showCloseButton={false}><DialogTitle className="sr-only">Rocket hardware explorer</DialogTitle><DialogDescription className="sr-only">Use the separation slider to inspect individual parts. Press Escape or Exit expanded view to close.</DialogDescription>{explorer}</DialogContent></Dialog>:explorer;
}
