<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Rocket 1</Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>14</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>654.1148764306521</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>200.0</KnownMass>
                    <Density>1250.0</Density>
                    <Material>PETG - 100% infill</Material>
                    <Name>Nose Cone</Name>
                    <KnownCG>205.92682285000342</KnownCG>
                    <UseKnownCG>1</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>916.2419783081266</CalcMass>
                    <CalcCG>205.92682285000342</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>300.00000000000006</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>1</ShapeCode>
                    <ConstructionType>0</ConstructionType>
                    <WallThickness>38.1</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>76.2</BaseDia>
                    <ShoulderLen>75.0</ShoulderLen>
                    <ShoulderOD>73.4</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>66.19154111925548</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>228.6</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>66.19154111925548</CalcMass>
                    <CalcCG>228.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>457.2</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>76.2</OD>
                    <ID>74.4</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>74.4</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>21.477821885973594</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Tube Coupler</Name>
                            <KnownCG>76.2</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-80.0</Xb>
                            <CalcMass>21.477821885973594</CalcMass>
                            <CalcCG>76.2</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>152.4</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>3</SerialNo>
                            <OD>74.2</OD>
                            <ID>72.4</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>327.39602499999995</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Shock Cord</Name>
                            <KnownCG>350.00000000000006</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>350.00000000000006</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <Parachute>
                            <KnownMass>46.31203545637582</KnownMass>
                            <Density>0.00527</Density>
                            <Material>Nylon fabric, ripstop, 1.7 oz actual</Material>
                            <Name>Parachute, 36 in., nylon, 8 lines</Name>
                            <KnownCG>12.5</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>80.00000000000004</Xb>
                            <CalcMass>46.31203545637582</CalcMass>
                            <CalcCG>12.5</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>5</SerialNo>
                            <Dia>914.4</Dia>
                            <ShroudLineCount>8</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>914.4</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>0.0016</ShroudLineMassPerMM>
                            <ShroudLineMaterial>Nylon Paracord, 110 lb, 1/16 in. dia.</ShroudLineMaterial>
                            <DragCoefficient>0.8</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>5.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>eyebolt</Name>
                            <KnownCG>48.000000000000014</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>48.000000000000014</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
                <BodyTube>
                    <KnownMass>144.94355470115914</KnownMass>
                    <Density>680.0</Density>
                    <Material>Cardboard</Material>
                    <Name>Body Tube</Name>
                    <KnownCG>228.6</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>144.94355470115914</CalcMass>
                    <CalcCG>228.6</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>457.2</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>7</SerialNo>
                    <OD>76.2</OD>
                    <ID>72.2</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>72.2</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>73.56825000000005</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Trapezoidal Fin Set</Name>
                            <KnownCG>117.72639691714836</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>73.56825000000005</CalcMass>
                            <CalcCG>117.72639691714836</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>8</SerialNo>
                            <FinCount>3</FinCount>
                            <RootChord>200.0000000000001</RootChord>
                            <TipChord>130.00000000000003</TipChord>
                            <SemiSpan>75.0</SemiSpan>
                            <SweepDistance>74.99999999999996</SweepDistance>
                            <Thickness>3.0</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>0</TipShapeCode>
                            <TabLength>60.0</TabLength>
                            <TabDepth>10.0</TabDepth>
                            <TabOffset>70.00000000000006</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <BodyTube>
                            <KnownMass>6.697247218922718</KnownMass>
                            <Density>680.0</Density>
                            <Material>Cardboard</Material>
                            <Name>Inner Tube</Name>
                            <KnownCG>110.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>6.697247218922718</CalcMass>
                            <CalcCG>110.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>220.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>28.999999999999996</OD>
                            <ID>27.999999999999996</ID>
                            <IsMotorMount>1</IsMotorMount>
                            <MotorDia>27.999999999999996</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                        <Ring>
                            <KnownMass>12.979140703203152</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering Ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>214.99999999999994</Xb>
                            <CalcMass>12.979140703203152</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>72.2</OD>
                            <ID>28.999999999999996</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>12.979140703203152</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering Ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>100.0</Xb>
                            <CalcMass>12.979140703203152</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>11</SerialNo>
                            <OD>72.2</OD>
                            <ID>28.999999999999996</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>12.979140703203152</KnownMass>
                            <Density>630.0</Density>
                            <Material>Plywood (birch)</Material>
                            <Name>Centering Ring</Name>
                            <KnownCG>3.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>10.0</Xb>
                            <CalcMass>12.979140703203152</CalcMass>
                            <CalcCG>3.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>6.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>72.2</OD>
                            <ID>28.999999999999996</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <MassObject>
                            <KnownMass>7.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>eyebolt</Name>
                            <KnownCG>220.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>220.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>13</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>4.0</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Blast Protector</Name>
                            <KnownCG>-107.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>-107.0</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>14</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>