import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
export const metadata: Metadata={title:"Robotics — Controls, Fabrication & Integration",description:"Martin Li’s UC Irvine robotics work: Arduino/C++ programming, feedback control, chassis fabrication, calibration, and hands-on mechanical troubleshooting."};
const photos=[
 {file:"robot.png",label:"THE PHYSICAL ROBOT",caption:"Our pneumatic robot, with the tire storing the compressed air that drives it.",alt:"Physical wheeled pneumatic robot with an upright tire, wooden chassis, and drive mechanism"},
 {file:"cad-side.png",label:"CAD / SYSTEM LAYOUT",caption:"The team’s CAD assembly shows how the tire, cylinder, chassis, and gear trains fit together.",alt:"Side view of the team’s CAD robot assembly and pneumatic drive"},
 {file:"cad-mechanism.png",label:"CAD / DRIVE MECHANISM",caption:"A closer look at the rack-and-pinion drive and the gears underneath.",alt:"Angled CAD view showing rack-and-pinion gearing beneath the robot’s tire"},
 {file:"wiring.png",label:"WIRING DIAGRAM",caption:"The electrical layout connecting the Arduino, heading sensor, steering servo, and solenoid driver.",alt:"Team wiring diagram of Arduino Uno, magnetometer, servo, MOSFET, solenoid and power supplies"}
];
export default function Robotics(){return <main id="main"><section className="project-heading shell"><Link href="/#projects" className="back-link"><ArrowLeft size={15}/>BACK TO PROJECTS</Link><div className="project-title-row"><div><p className="eyebrow">02 / ROBOTICS</p><h1>Code meets hardware.</h1></div><div className="project-title-detail"><p>UC Irvine · MAE 106</p><span>ACADEMIC PROJECT · UNPAID</span></div></div></section>
<section className="project-detail-body shell"><p className="eyebrow">01 / PNEUMATIC MOBILE ROBOT</p><h2 className="robot-project-title">Controls, fabrication & integration.</h2><p className="detail-lead">Developed the main control program and fabricated chassis components for a three-person pneumatic robot project. Combined Arduino/C++ programming, calibration, and hands-on mechanical repairs to help turn a team design into working hardware.</p><div className="detail-columns"><div><h2>My contribution</h2><ul className="experience-points"><li><strong>Control programming.</strong> Wrote the main Arduino/C++ program for the robot, with timed solenoid actuation, heading-based steering, and distance-based navigation.</li><li><strong>Calibration and debugging.</strong> Adjusted control parameters with teammate support to bring the program and physical robot into alignment.</li><li><strong>Chassis fabrication.</strong> Cut and sanded the upper and lower circular wooden plates and structural support columns.</li><li><strong>Mechanical troubleshooting.</strong> Replaced failed supports made from 3D-printed parts and aluminum rods with wooden columns, helping restore the assembly.</li></ul><div className="role-skills"><span>Arduino / C++</span><span>Feedback control</span><span>Sensor integration</span><span>Calibration</span><span>Wood fabrication</span><span>Mechanical troubleshooting</span></div></div><div><h2>How the robot works</h2><p>A compressed-air tire supplies a pneumatic cylinder. A rack-and-pinion mechanism drives two gear trains, using both the powered stroke and the spring return. The team used a 3:1 ratio on the powered side and 1:4 on the return side to balance speed and torque.</p><p>The control system combines a steering servo, magnetometer/IMU heading feedback, wheel-switch distance measurement, and a timed solenoid. The final program sequences straight travel and two 90-degree turns.</p><p className="robot-team-credit">Team: Martin Li, Adam Diersing, and Logan Bigler. Logan led CAD and drivetrain design; Adam handled wiring, electrical work, test data, and final code fixes.</p><a className="text-link" href="/files/mae-106-final-report.pdf" target="_blank" rel="noopener noreferrer">Read the team’s final report<ArrowUpRight size={16}/></a></div></div>
<div className="robot-results"><div><p className="eyebrow">TEAM TEST RESULT</p><h2>6.77 seconds over 10 feet.</h2><p>The best tested setting averaged <strong>6.774 s across 10 runs</strong>, with a standard deviation of <strong>0.156 s</strong>. Tests used a 40% solenoid duty cycle, a 750 ms period, 40 psi starting pressure, and a heading-control gain of 0.6.</p><p>This setting also showed the lowest variation among the tested configurations. It was selected for the final program.</p><p className="robot-team-credit">Experimental testing and analysis: Adam Diersing. Results describe the team’s robot.</p></div><figure><a href="/gallery/robotics/test-results.png" target="_blank" rel="noopener noreferrer" aria-label="Open full team performance graph"><img src="/gallery/robotics/test-results.png" alt="Report graph of mean time to travel ten feet versus solenoid duty cycle at a 750 millisecond period, with one-standard-deviation error bars" loading="lazy" width="546" height="415"/></a><figcaption>Team report: 750 ms period, ten trials per setting. Lower time is faster.</figcaption></figure></div></section>
<section className="flight-journal shell" aria-labelledby="robot-gallery-title"><div className="journal-heading"><p className="eyebrow">FROM THE PROJECT REPORT</p><h2 id="robot-gallery-title">The build, the CAD & the wiring.</h2><p>Physical hardware and team design documentation from our MAE 106 final report.</p></div><div className="journal-grid">{photos.map((photo,i)=><figure className="journal-entry" key={photo.file}><a href={`/gallery/robotics/${photo.file}`} target="_blank" rel="noopener noreferrer" aria-label={`Open full image: ${photo.alt}`}><img src={`/gallery/robotics/${photo.file}`} alt={photo.alt} loading="lazy"/></a><figcaption><span>{String(i+1).padStart(2,'0')} / {photo.label}</span>{photo.caption}</figcaption></figure>)}</div></section>
<section className="project-detail-body shell"><p className="eyebrow">02 / EARLIER ROBOTICS WORK</p><h2 className="robot-project-title">Two-legged running robot.</h2><p className="detail-lead">In a separate UC Irvine project, I led an eight-person team through mechanical design, fabrication, and assembly of a two-legged running robot.</p><p className="robot-earlier-copy">Modeled components and the assembly in SolidWorks, integrated 3D-printed and woodcut parts, and used hand tools, precision fasteners, and fit checks to refine the physical build.</p></section>
<section className="project-end shell"><Link href="/projects/rocket" className="text-link"><ArrowLeft size={16}/>Rocket project</Link><Link href="/projects/cisco-antigua" className="text-link">Cisco Antigua<ArrowUpRight size={16}/></Link></section></main>}
