import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft, ArrowUpRight } from "lucide-react";
export const metadata: Metadata={title:"Cisco Antigua — Computers for the World",description:"Martin Li’s volunteer networking work with the Rotary Computers for the World initiative in Antigua and Barbuda, with program impact, news coverage, and field photos."};
const coverage=[
 {name:"Rotary Club of Antigua",kind:"OFFICIAL PROJECT PARTNER · FEBRUARY 2017",title:"Computers for the World",note:"The project’s early history: 2,400 computers and more than 50 networked labs by 2017.",url:"https://rotaryclubantigua.org/stories/computers-for-the-world"},
 {name:"Bellevue Breakfast Rotary Club",kind:"OFFICIAL PROJECT PARTNER · FEBRUARY 2025",title:"Improving Antigua’s Schools with Technology Once Again — in 2025!",note:"An update from the organizers on the Rotary and Newport High School partnership.",url:"https://bbrc.net/event/improving-antiguas-schools-with-technology-once-again-in-2025/"},
 {name:"ABS TV / Radio",kind:"LOCAL TELEVISION · AB TODAY",title:"Education Through Technology interview",note:"Cordell Josiah, Jeff Mason, and Jan Martinka discuss the initiative on AB Today.",url:"https://www.facebook.com/abstvradio/videos/ab-today-cordell-josiah-jeff-mason-jan-martinka-rotary-club-of-antigua-education/929378579957928/"},
 {name:"Antigua Observer",kind:"NEWSPAPER · FEBRUARY 2025",title:"Education Through Technology continues to deliver laptops and network infrastructure",note:"Reports approximately 10,000 computers distributed since the program began, plus the 2025 installation.",url:"https://antiguaobserver.com/rcas-education-through-technology-initiative-continues-to-deliver-laptops-vital-network-infrastructure-to-schools/"},
 {name:"Bellevue Reporter",kind:"LOCAL NEWSPAPER · MARCH 2009",title:"Bellevue Breakfast Rotary Club and Newport High students take computers to Antigua",note:"Early reporting on the partnership and school technology donations.",url:"https://www.bellevuereporter.com/2009/03/17/bellevue-breakfast-rotary-club-newport-high-students-to-take-computers-dictionaires-to-antigua/"},
 {name:"Antigua News Room",kind:"LOCAL NEWS · JANUARY 2021",title:"Rotary Club of Antigua donates technological equipment to educational institutions",note:"Coverage of the club’s educational equipment donations.",url:"https://antiguanewsroom.com/rotary-club-of-antigua-donates-technological-equipment-to-educational-institutions/"},
 {name:"Martinka Consulting",kind:"PROJECT ORGANIZER’S ACCOUNT · MARCH 2012",title:"Rotary Project in Antigua",note:"John Martinka describes computer labs, inter-island video conferencing, and the team’s television appearance in 2012.",url:"https://www.martinkaconsulting.com/rotary-project-in-antigua/"}
];
const equipment=[
 {file:"26065.jpg",label:"WORKING WITH THE SPACE",caption:"A small desk, a few cables, and a network to get connected.",alt:"Networking equipment and coiled cables on a desk beside a classroom window"},
 {file:"26063.jpg",label:"CLASSROOM CONNECTIVITY",caption:"The classroom setup—this is where the networking work ends up.",alt:"Wall-mounted wireless networking equipment and cabling above classroom posters"}
];
const people=[
 {file:"26062.jpg",label:"AT THE SCHOOL",caption:"One of my favorite parts: meeting the students we were there to support.",alt:"The volunteer team standing with local students in school uniform"},
 {file:"26003.jpg",label:"WITH OUR HOSTS",caption:"Getting everyone together with our Rotary hosts.",alt:"Volunteers and local hosts gathered indoors beside a Rotary Club of Antigua banner"},
 {file:"26074.jpg",label:"THE TEAM",caption:"A quick team photo, with quite a view behind us.",alt:"The volunteer team in yellow shirts overlooking Antigua’s coastline"},
 {file:"26005.jpg",label:"OUT TOGETHER",caption:"A quick group selfie along the way.",alt:"Students and team members posing for a group selfie outdoors"},
 {file:"26120.jpg",label:"AFTER THE DAY’S WORK",caption:"Ending the day together by the water.",alt:"Team members and companions posing on a beach at sunset"},
 {file:"26078.jpg",label:"ON THE MOVE",caption:"The whole crew, bags and all.",alt:"The volunteer group with luggage at an airport terminal"}
];
function Gallery({photos}:{photos:typeof equipment}){return <div className="journal-grid">{photos.map((photo,i)=><figure className="journal-entry" key={photo.file}><a href={`/gallery/antigua/${photo.file}`} target="_blank" rel="noopener noreferrer" aria-label={`Open full photo: ${photo.alt}`}><img src={`/gallery/antigua/${photo.file}`} alt={photo.alt} loading="lazy"/></a><figcaption><span>{String(i+1).padStart(2,'0')} / {photo.label}</span>{photo.caption}</figcaption></figure>)}</div>}
export default function CiscoAntigua(){return <main id="main">
 <section className="project-heading shell"><Link href="/#projects" className="back-link"><ArrowLeft size={15}/>BACK TO PROJECTS</Link><div className="project-title-row"><div><p className="eyebrow">03 / COMMUNITY & HARDWARE</p><h1>Technology, put to use.</h1></div><div className="project-title-detail"><p>Cisco Antigua · Computers for the World</p><span>2023 DONATION TRIP · VOLUNTEER · UNPAID</span></div></div></section>
 <section className="project-detail-body shell"><p className="detail-lead">In 2023, I joined the Rotary school technology donation initiative in Antigua and Barbuda, combining hands-on Cisco networking with volunteer team leadership. The goal was practical: help donated equipment become working connections that students and teachers could use.</p>
 <div className="detail-columns"><div><h2>My contribution</h2><ul className="experience-points"><li>Configured and deployed more than 50 Cisco routers and access points.</li><li>Led a ten-person team and helped coordinate more than 200 donated routers and projectors.</li><li>Worked with project partners and local stakeholders on equipment preparation and deployment logistics.</li><li>Applied networking knowledge to configuration, connectivity checks, and troubleshooting in schools.</li></ul></div><div><h2>A partnership built over years.</h2><p>Beginning in 2008, the Rotary Club of Antigua and Washington State’s Bellevue Breakfast Rotary Club brought together local school partners, Rotarians led by John Martinka, and Newport High School’s Cisco networking students and teachers led by Jeff Mason. The initiative supports government and private schools across Antigua and Barbuda. <a className="inline-source" href={coverage[0].url} target="_blank" rel="noopener noreferrer">Rotary project history ↗</a></p><p>The wider program has included computer donations, new and upgraded labs, wired and wireless networks, and video conferencing between the islands for teaching and teacher training. <a className="inline-source" href={coverage[6].url} target="_blank" rel="noopener noreferrer">Organizer’s field account ↗</a></p></div></div>
 <div className="program-impact"><p className="eyebrow">PROGRAM-WIDE IMPACT / REPORTED MILESTONES</p><div className="detail-facts"><div><strong>≈10,000</strong><span>Computers distributed since 2008, reported February 2025</span></div><div><strong>1,500</strong><span>Laptops in the 2025 installation, reported by Antigua Observer</span></div><div><strong>50+</strong><span>Networked computer labs established by February 2017</span></div></div><p>These figures describe the wider initiative across multiple years. <a className="inline-source" href={coverage[3].url} target="_blank" rel="noopener noreferrer">2025 reporting ↗</a> · <a className="inline-source" href={coverage[0].url} target="_blank" rel="noopener noreferrer">2017 Rotary account ↗</a></p></div>
 <div className="antigua-highlights"><article><p className="eyebrow">THE WELCOME</p><h3>More than a technical trip.</h3><p>Our 2023 team was personally greeted by the Prime Minister of Antigua and Barbuda over lunch—a highlight of the trip and a chance to connect with our hosts beyond the school installations.</p></article><article><p className="eyebrow">ON LOCAL TELEVISION</p><h3>Our project reached local TV.</h3><p>The initiative has been featured by ABS TV / Radio, bringing the school technology work to a wider local audience.</p><a className="text-link" href={coverage[2].url} target="_blank" rel="noopener noreferrer">Watch the AB Today interview<ArrowUpRight size={15}/></a></article></div>
 <details className="project-history"><summary>From Rotary’s 2017 project account</summary><p className="history-date">Published February 20, 2017. The “tenth year” and totals below refer to that historical report.</p><blockquote><p>The <strong>Rotary Club of Antigua</strong> in partnership with the <strong>Belleview Breakfast Rotary Club</strong> of Washington State is in its tenth (10) year of conducting the Computer for the World Project which started in 2008.</p><p>In this project a team of <strong>Rotarians headed by Mr. John Martinka</strong> of the Belleview Breakfast Rotary Club along with and a team of <strong>Cisco Systems IT Students and Teachers</strong> headed by <strong>Mr. Jeff Mason</strong> from the Newport High School in Belleview, Washington State have been coming to Antigua &amp; Barbuda and have been installing computers in Government and Private Schools as a donation to the Ministry of Education for the Students of Antigua &amp; Barbuda.</p><p>To date over the years, some two thousand, four hundred <strong>(2,400)</strong> computers have been installed and over <strong>50 fully networked computer labs</strong> have been set up in the schools in Antigua and in Barbuda.</p></blockquote><a href={coverage[0].url} target="_blank" rel="noopener noreferrer" className="inline-source">Read the original Rotary account ↗</a></details>
 </section>
 <section className="coverage-section shell" aria-labelledby="coverage-title"><p className="eyebrow">PROJECT PARTNERS & PRESS</p><h2 id="coverage-title">The initiative, in the news.</h2><p className="coverage-intro">Official project partners first, followed by broadcast and newspaper coverage, then a personal account from an organizer. These reports document different years of the wider program.</p><ol className="coverage-list">{coverage.map((item,i)=><li key={item.url}><a href={item.url} target="_blank" rel="noopener noreferrer"><span className="coverage-number">{String(i+1).padStart(2,'0')}</span><div><p className="eyebrow">{item.kind}</p><h3>{item.name}</h3><p>{item.title}</p><small>{item.note}</small></div><ArrowUpRight size={19}/></a></li>)}</ol></section>
 <section className="flight-journal shell" aria-labelledby="devices-title"><div className="journal-heading"><p className="eyebrow">2023 PHOTO JOURNAL / 01</p><h2 id="devices-title">Devices, routers & classroom networks.</h2><p>A couple of details from the installations.</p></div><Gallery photos={equipment}/></section>
 <section className="flight-journal shell" aria-labelledby="people-title"><div className="journal-heading"><p className="eyebrow">2023 PHOTO JOURNAL / 02</p><h2 id="people-title">The people who made the trip.</h2><p>Our team, local students, and the people who welcomed us.</p></div><Gallery photos={people}/></section>
 <section className="project-end shell"><Link href="/projects/robotics" className="text-link"><ArrowLeft size={16}/>Robotics</Link><Link href="/#contact" className="text-link">Contact Martin<ArrowUpRight size={16}/></Link></section>
 </main>}
